// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bankroll.sql

package store

import (
	"context"
	"encoding/json"
)

const getBankrollBalanceCents = `-- name: GetBankrollBalanceCents :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS balance_cents
FROM bankroll_ledger
`

func (q *Queries) GetBankrollBalanceCents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getBankrollBalanceCents)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const getBankrollCircuitMetrics = `-- name: GetBankrollCircuitMetrics :one
WITH anchor AS (
    SELECT
        NOW() AS now_ts,
        DATE_TRUNC('day', NOW()) AS day_start_ts,
        DATE_TRUNC('week', NOW()) AS week_start_ts
),
ledger_totals AS (
    SELECT
        COALESCE(SUM(amount_cents), 0)::BIGINT AS current_balance_cents,
        COALESCE(SUM(amount_cents) FILTER (WHERE created_at < (SELECT day_start_ts FROM anchor)), 0)::BIGINT AS day_start_balance_cents,
        COALESCE(SUM(amount_cents) FILTER (WHERE created_at < (SELECT week_start_ts FROM anchor)), 0)::BIGINT AS week_start_balance_cents
    FROM bankroll_ledger
),
running_balance AS (
    SELECT
        SUM(amount_cents) OVER (ORDER BY created_at ASC, id ASC) AS balance_after_cents
    FROM bankroll_ledger
),
peak_balance AS (
    SELECT
        COALESCE(MAX(balance_after_cents), 0)::BIGINT AS peak_balance_cents
    FROM running_balance
)
SELECT
    l.current_balance_cents,
    l.day_start_balance_cents,
    l.week_start_balance_cents,
    p.peak_balance_cents
FROM ledger_totals l
CROSS JOIN peak_balance p
`

type GetBankrollCircuitMetricsRow struct {
	CurrentBalanceCents   int64 `json:"current_balance_cents"`
	DayStartBalanceCents  int64 `json:"day_start_balance_cents"`
	WeekStartBalanceCents int64 `json:"week_start_balance_cents"`
	PeakBalanceCents      int64 `json:"peak_balance_cents"`
}

func (q *Queries) GetBankrollCircuitMetrics(ctx context.Context) (GetBankrollCircuitMetricsRow, error) {
	row := q.db.QueryRow(ctx, getBankrollCircuitMetrics)
	var i GetBankrollCircuitMetricsRow
	err := row.Scan(
		&i.CurrentBalanceCents,
		&i.DayStartBalanceCents,
		&i.WeekStartBalanceCents,
		&i.PeakBalanceCents,
	)
	return i, err
}

const insertBankrollEntry = `-- name: InsertBankrollEntry :one
INSERT INTO bankroll_ledger (
    entry_type,
    amount_cents,
    currency,
    reference_type,
    reference_id,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, entry_type, amount_cents, currency, reference_type, reference_id, metadata, created_at
`

type InsertBankrollEntryParams struct {
	EntryType     string          `json:"entry_type"`
	AmountCents   int64           `json:"amount_cents"`
	Currency      string          `json:"currency"`
	ReferenceType string          `json:"reference_type"`
	ReferenceID   string          `json:"reference_id"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) InsertBankrollEntry(ctx context.Context, arg InsertBankrollEntryParams) (BankrollLedger, error) {
	row := q.db.QueryRow(ctx, insertBankrollEntry,
		arg.EntryType,
		arg.AmountCents,
		arg.Currency,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
	)
	var i BankrollLedger
	err := row.Scan(
		&i.ID,
		&i.EntryType,
		&i.AmountCents,
		&i.Currency,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listBankrollEntries = `-- name: ListBankrollEntries :many
SELECT id, entry_type, amount_cents, currency, reference_type, reference_id, metadata, created_at
FROM bankroll_ledger
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListBankrollEntries(ctx context.Context, rowLimit int32) ([]BankrollLedger, error) {
	rows, err := q.db.Query(ctx, listBankrollEntries, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankrollLedger
	for rows.Next() {
		var i BankrollLedger
		if err := rows.Scan(
			&i.ID,
			&i.EntryType,
			&i.AmountCents,
			&i.Currency,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
