// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bankroll.sql

package store

import (
	"context"
	"encoding/json"
)

const getBankrollBalanceCents = `-- name: GetBankrollBalanceCents :one
SELECT COALESCE(SUM(amount_cents), 0)::BIGINT AS balance_cents
FROM bankroll_ledger
`

func (q *Queries) GetBankrollBalanceCents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getBankrollBalanceCents)
	var balance_cents int64
	err := row.Scan(&balance_cents)
	return balance_cents, err
}

const insertBankrollEntry = `-- name: InsertBankrollEntry :one
INSERT INTO bankroll_ledger (
    entry_type,
    amount_cents,
    currency,
    reference_type,
    reference_id,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, entry_type, amount_cents, currency, reference_type, reference_id, metadata, created_at
`

type InsertBankrollEntryParams struct {
	EntryType     string          `json:"entry_type"`
	AmountCents   int64           `json:"amount_cents"`
	Currency      string          `json:"currency"`
	ReferenceType string          `json:"reference_type"`
	ReferenceID   string          `json:"reference_id"`
	Metadata      json.RawMessage `json:"metadata"`
}

func (q *Queries) InsertBankrollEntry(ctx context.Context, arg InsertBankrollEntryParams) (BankrollLedger, error) {
	row := q.db.QueryRow(ctx, insertBankrollEntry,
		arg.EntryType,
		arg.AmountCents,
		arg.Currency,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
	)
	var i BankrollLedger
	err := row.Scan(
		&i.ID,
		&i.EntryType,
		&i.AmountCents,
		&i.Currency,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
