// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bets.sql

package store

import (
	"context"
	"encoding/json"
)

const getBetByIdempotencyKey = `-- name: GetBetByIdempotencyKey :one
SELECT id, idempotency_key, snapshot_id, game_id, sport, market_key,
    recommended_side, book_key, american_odds, stake_cents,
    model_probability, market_probability, edge, status, external_bet_id,
    adapter_name, placed_at, settled_at, settlement_result, payout_cents,
    clv_delta, closing_probability, error_message, metadata, created_at, updated_at
FROM bets
WHERE idempotency_key = $1
`

func (q *Queries) GetBetByIdempotencyKey(ctx context.Context, idempotencyKey string) (Bet, error) {
	row := q.db.QueryRow(ctx, getBetByIdempotencyKey, idempotencyKey)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.SnapshotID,
		&i.GameID,
		&i.Sport,
		&i.MarketKey,
		&i.RecommendedSide,
		&i.BookKey,
		&i.AmericanOdds,
		&i.StakeCents,
		&i.ModelProbability,
		&i.MarketProbability,
		&i.Edge,
		&i.Status,
		&i.ExternalBetID,
		&i.AdapterName,
		&i.PlacedAt,
		&i.SettledAt,
		&i.SettlementResult,
		&i.PayoutCents,
		&i.ClvDelta,
		&i.ClosingProbability,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBet = `-- name: InsertBet :one
INSERT INTO bets (
    idempotency_key, snapshot_id, game_id, sport, market_key,
    recommended_side, book_key, american_odds, stake_cents,
    model_probability, market_probability, edge, status, adapter_name, metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, 'pending', $13, $14
)
RETURNING id, idempotency_key, snapshot_id, game_id, sport, market_key,
    recommended_side, book_key, american_odds, stake_cents,
    model_probability, market_probability, edge, status, external_bet_id,
    adapter_name, placed_at, settled_at, settlement_result, payout_cents,
    clv_delta, closing_probability, error_message, metadata, created_at, updated_at
`

type InsertBetParams struct {
	IdempotencyKey    string          `json:"idempotency_key"`
	SnapshotID        int64           `json:"snapshot_id"`
	GameID            int64           `json:"game_id"`
	Sport             string          `json:"sport"`
	MarketKey         string          `json:"market_key"`
	RecommendedSide   string          `json:"recommended_side"`
	BookKey           string          `json:"book_key"`
	AmericanOdds      int32           `json:"american_odds"`
	StakeCents        int64           `json:"stake_cents"`
	ModelProbability  float64         `json:"model_probability"`
	MarketProbability float64         `json:"market_probability"`
	Edge              float64         `json:"edge"`
	AdapterName       string          `json:"adapter_name"`
	Metadata          json.RawMessage `json:"metadata"`
}

func (q *Queries) InsertBet(ctx context.Context, arg InsertBetParams) (Bet, error) {
	row := q.db.QueryRow(ctx, insertBet,
		arg.IdempotencyKey,
		arg.SnapshotID,
		arg.GameID,
		arg.Sport,
		arg.MarketKey,
		arg.RecommendedSide,
		arg.BookKey,
		arg.AmericanOdds,
		arg.StakeCents,
		arg.ModelProbability,
		arg.MarketProbability,
		arg.Edge,
		arg.AdapterName,
		arg.Metadata,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.SnapshotID,
		&i.GameID,
		&i.Sport,
		&i.MarketKey,
		&i.RecommendedSide,
		&i.BookKey,
		&i.AmericanOdds,
		&i.StakeCents,
		&i.ModelProbability,
		&i.MarketProbability,
		&i.Edge,
		&i.Status,
		&i.ExternalBetID,
		&i.AdapterName,
		&i.PlacedAt,
		&i.SettledAt,
		&i.SettlementResult,
		&i.PayoutCents,
		&i.ClvDelta,
		&i.ClosingProbability,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBetsByStatus = `-- name: ListBetsByStatus :many
SELECT id, idempotency_key, snapshot_id, game_id, sport, market_key,
    recommended_side, book_key, american_odds, stake_cents,
    model_probability, market_probability, edge, status, external_bet_id,
    adapter_name, placed_at, settled_at, settlement_result, payout_cents,
    clv_delta, closing_probability, error_message, metadata, created_at, updated_at
FROM bets
WHERE status = $1::bet_status
ORDER BY created_at DESC
LIMIT $2
`

type ListBetsByStatusParams struct {
	Status   BetStatus `json:"status"`
	RowLimit int32     `json:"row_limit"`
}

func (q *Queries) ListBetsByStatus(ctx context.Context, arg ListBetsByStatusParams) ([]Bet, error) {
	rows, err := q.db.Query(ctx, listBetsByStatus, arg.Status, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bet
	for rows.Next() {
		var i Bet
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.SnapshotID,
			&i.GameID,
			&i.Sport,
			&i.MarketKey,
			&i.RecommendedSide,
			&i.BookKey,
			&i.AmericanOdds,
			&i.StakeCents,
			&i.ModelProbability,
			&i.MarketProbability,
			&i.Edge,
			&i.Status,
			&i.ExternalBetID,
			&i.AdapterName,
			&i.PlacedAt,
			&i.SettledAt,
			&i.SettlementResult,
			&i.PayoutCents,
			&i.ClvDelta,
			&i.ClosingProbability,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenBets = `-- name: ListOpenBets :many
SELECT id, idempotency_key, snapshot_id, game_id, sport, market_key,
    recommended_side, book_key, american_odds, stake_cents,
    model_probability, market_probability, edge, status, external_bet_id,
    adapter_name, placed_at, settled_at, settlement_result, payout_cents,
    clv_delta, closing_probability, error_message, metadata, created_at, updated_at
FROM bets
WHERE status = 'placed'
ORDER BY created_at ASC
`

func (q *Queries) ListOpenBets(ctx context.Context) ([]Bet, error) {
	rows, err := q.db.Query(ctx, listOpenBets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bet
	for rows.Next() {
		var i Bet
		if err := rows.Scan(
			&i.ID,
			&i.IdempotencyKey,
			&i.SnapshotID,
			&i.GameID,
			&i.Sport,
			&i.MarketKey,
			&i.RecommendedSide,
			&i.BookKey,
			&i.AmericanOdds,
			&i.StakeCents,
			&i.ModelProbability,
			&i.MarketProbability,
			&i.Edge,
			&i.Status,
			&i.ExternalBetID,
			&i.AdapterName,
			&i.PlacedAt,
			&i.SettledAt,
			&i.SettlementResult,
			&i.PayoutCents,
			&i.ClvDelta,
			&i.ClosingProbability,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBetFailed = `-- name: UpdateBetFailed :exec
UPDATE bets
SET status = 'failed', error_message = $1, updated_at = NOW()
WHERE id = $2 AND status = 'pending'
`

type UpdateBetFailedParams struct {
	ErrorMessage *string `json:"error_message"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateBetFailed(ctx context.Context, arg UpdateBetFailedParams) error {
	_, err := q.db.Exec(ctx, updateBetFailed, arg.ErrorMessage, arg.ID)
	return err
}

const updateBetPlaced = `-- name: UpdateBetPlaced :exec
UPDATE bets
SET status = 'placed', external_bet_id = $1, placed_at = NOW(), updated_at = NOW()
WHERE id = $2 AND status = 'pending'
`

type UpdateBetPlacedParams struct {
	ExternalBetID *string `json:"external_bet_id"`
	ID            int64   `json:"id"`
}

func (q *Queries) UpdateBetPlaced(ctx context.Context, arg UpdateBetPlacedParams) error {
	_, err := q.db.Exec(ctx, updateBetPlaced, arg.ExternalBetID, arg.ID)
	return err
}

const updateBetSettled = `-- name: UpdateBetSettled :exec
UPDATE bets
SET status = 'settled', settlement_result = $1, payout_cents = $2,
    clv_delta = $3, closing_probability = $4, settled_at = NOW(), updated_at = NOW()
WHERE id = $5 AND status = 'placed'
`

type UpdateBetSettledParams struct {
	SettlementResult   *string  `json:"settlement_result"`
	PayoutCents        *int64   `json:"payout_cents"`
	ClvDelta           *float64 `json:"clv_delta"`
	ClosingProbability *float64 `json:"closing_probability"`
	ID                 int64    `json:"id"`
}

func (q *Queries) UpdateBetSettled(ctx context.Context, arg UpdateBetSettledParams) error {
	_, err := q.db.Exec(ctx, updateBetSettled,
		arg.SettlementResult,
		arg.PayoutCents,
		arg.ClvDelta,
		arg.ClosingProbability,
		arg.ID,
	)
	return err
}
