// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dashboard.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completePollRun = `-- name: CompletePollRun :exec
UPDATE poll_runs
SET
    finished_at = $2,
    status = $3,
    games_seen = $4,
    snapshots_seen = $5,
    inserts_count = $6,
    dedup_skips = $7,
    error_text = $8
WHERE id = $1
`

type CompletePollRunParams struct {
	ID            int64              `json:"id"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Status        string             `json:"status"`
	GamesSeen     int32              `json:"games_seen"`
	SnapshotsSeen int32              `json:"snapshots_seen"`
	InsertsCount  int32              `json:"inserts_count"`
	DedupSkips    int32              `json:"dedup_skips"`
	ErrorText     string             `json:"error_text"`
}

func (q *Queries) CompletePollRun(ctx context.Context, arg CompletePollRunParams) error {
	_, err := q.db.Exec(ctx, completePollRun,
		arg.ID,
		arg.FinishedAt,
		arg.Status,
		arg.GamesSeen,
		arg.SnapshotsSeen,
		arg.InsertsCount,
		arg.DedupSkips,
		arg.ErrorText,
	)
	return err
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT
    (SELECT COUNT(*)::BIGINT FROM games WHERE commence_time >= NOW() - INTERVAL '7 days') AS games_count,
    (SELECT COUNT(*)::BIGINT FROM odds_history) AS snapshots_count,
    (SELECT MAX(captured_at)::timestamptz FROM odds_history) AS last_snapshot_at
`

type GetDashboardSummaryRow struct {
	GamesCount     int64              `json:"games_count"`
	SnapshotsCount int64              `json:"snapshots_count"`
	LastSnapshotAt pgtype.Timestamptz `json:"last_snapshot_at"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary)
	var i GetDashboardSummaryRow
	err := row.Scan(&i.GamesCount, &i.SnapshotsCount, &i.LastSnapshotAt)
	return i, err
}

const getLatestPollRun = `-- name: GetLatestPollRun :one
SELECT id, source, started_at, finished_at, status, games_seen, snapshots_seen, inserts_count, dedup_skips, error_text
FROM poll_runs
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPollRun(ctx context.Context) (PollRun, error) {
	row := q.db.QueryRow(ctx, getLatestPollRun)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.GamesSeen,
		&i.SnapshotsSeen,
		&i.InsertsCount,
		&i.DedupSkips,
		&i.ErrorText,
	)
	return i, err
}

const getOddsArchiveSummary = `-- name: GetOddsArchiveSummary :one
SELECT
    COUNT(*)::BIGINT AS snapshots_count,
    MAX(oh.captured_at)::timestamptz AS last_snapshot_at
FROM odds_history AS oh
JOIN games AS g ON g.id = oh.game_id
WHERE
    $1::text IS NULL
    OR g.sport = $1::text
`

type GetOddsArchiveSummaryRow struct {
	SnapshotsCount int64              `json:"snapshots_count"`
	LastSnapshotAt pgtype.Timestamptz `json:"last_snapshot_at"`
}

func (q *Queries) GetOddsArchiveSummary(ctx context.Context, sport *string) (GetOddsArchiveSummaryRow, error) {
	row := q.db.QueryRow(ctx, getOddsArchiveSummary, sport)
	var i GetOddsArchiveSummaryRow
	err := row.Scan(&i.SnapshotsCount, &i.LastSnapshotAt)
	return i, err
}

const insertPollRun = `-- name: InsertPollRun :one
INSERT INTO poll_runs (
    source,
    started_at
) VALUES (
    $1,
    $2
)
RETURNING id, source, started_at, finished_at, status, games_seen, snapshots_seen, inserts_count, dedup_skips, error_text
`

type InsertPollRunParams struct {
	Source    string             `json:"source"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) InsertPollRun(ctx context.Context, arg InsertPollRunParams) (PollRun, error) {
	row := q.db.QueryRow(ctx, insertPollRun, arg.Source, arg.StartedAt)
	var i PollRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.GamesSeen,
		&i.SnapshotsSeen,
		&i.InsertsCount,
		&i.DedupSkips,
		&i.ErrorText,
	)
	return i, err
}
