// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: games.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUpcomingGames = `-- name: ListUpcomingGames :many
SELECT id, source, external_id, sport, home_team, away_team, commence_time, created_at, updated_at
FROM games
WHERE commence_time >= NOW() - INTERVAL '12 hours'
ORDER BY commence_time ASC
LIMIT $1
`

func (q *Queries) ListUpcomingGames(ctx context.Context, limit int32) ([]Game, error) {
	rows, err := q.db.Query(ctx, listUpcomingGames, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Sport,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.CommenceTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingGamesForSport = `-- name: ListUpcomingGamesForSport :many
SELECT id, source, external_id, sport, home_team, away_team, commence_time, created_at, updated_at
FROM games
WHERE sport = $1
  AND commence_time > NOW()
  AND commence_time < NOW() + INTERVAL '48 hours'
ORDER BY commence_time ASC
`

func (q *Queries) ListUpcomingGamesForSport(ctx context.Context, sport string) ([]Game, error) {
	rows, err := q.db.Query(ctx, listUpcomingGamesForSport, sport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Sport,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.CommenceTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGame = `-- name: UpsertGame :one
INSERT INTO games (
    source,
    external_id,
    sport,
    home_team,
    away_team,
    commence_time
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (source, external_id) DO UPDATE
SET
    sport = EXCLUDED.sport,
    home_team = EXCLUDED.home_team,
    away_team = EXCLUDED.away_team,
    commence_time = EXCLUDED.commence_time,
    updated_at = NOW()
RETURNING id, source, external_id, sport, home_team, away_team, commence_time, created_at, updated_at
`

type UpsertGameParams struct {
	Source       string             `json:"source"`
	ExternalID   string             `json:"external_id"`
	Sport        string             `json:"sport"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	CommenceTime pgtype.Timestamptz `json:"commence_time"`
}

func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, upsertGame,
		arg.Source,
		arg.ExternalID,
		arg.Sport,
		arg.HomeTeam,
		arg.AwayTeam,
		arg.CommenceTime,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Sport,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.CommenceTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
