// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: injuries.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertPlayerInjuryReport = `-- name: UpsertPlayerInjuryReport :exec
INSERT INTO player_injury_reports (
    source,
    sport,
    report_date,
    external_id,
    player_name,
    team_external_id,
    position,
    injury,
    status,
    estimated_return,
    player_url,
    raw_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (source, sport, report_date, external_id) DO UPDATE
SET
    player_name = EXCLUDED.player_name,
    team_external_id = EXCLUDED.team_external_id,
    position = EXCLUDED.position,
    injury = EXCLUDED.injury,
    status = EXCLUDED.status,
    estimated_return = EXCLUDED.estimated_return,
    player_url = EXCLUDED.player_url,
    raw_json = EXCLUDED.raw_json,
    updated_at = NOW()
WHERE
    player_injury_reports.player_name IS DISTINCT FROM EXCLUDED.player_name
    OR player_injury_reports.team_external_id IS DISTINCT FROM EXCLUDED.team_external_id
    OR player_injury_reports.position IS DISTINCT FROM EXCLUDED.position
    OR player_injury_reports.injury IS DISTINCT FROM EXCLUDED.injury
    OR player_injury_reports.status IS DISTINCT FROM EXCLUDED.status
    OR player_injury_reports.estimated_return IS DISTINCT FROM EXCLUDED.estimated_return
    OR player_injury_reports.player_url IS DISTINCT FROM EXCLUDED.player_url
    OR player_injury_reports.raw_json IS DISTINCT FROM EXCLUDED.raw_json
`

type UpsertPlayerInjuryReportParams struct {
	Source          string          `json:"source"`
	Sport           string          `json:"sport"`
	ReportDate      pgtype.Date     `json:"report_date"`
	ExternalID      string          `json:"external_id"`
	PlayerName      string          `json:"player_name"`
	TeamExternalID  string          `json:"team_external_id"`
	Position        string          `json:"position"`
	Injury          string          `json:"injury"`
	Status          string          `json:"status"`
	EstimatedReturn *string         `json:"estimated_return"`
	PlayerUrl       string          `json:"player_url"`
	RawJson         json.RawMessage `json:"raw_json"`
}

func (q *Queries) UpsertPlayerInjuryReport(ctx context.Context, arg UpsertPlayerInjuryReportParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerInjuryReport,
		arg.Source,
		arg.Sport,
		arg.ReportDate,
		arg.ExternalID,
		arg.PlayerName,
		arg.TeamExternalID,
		arg.Position,
		arg.Injury,
		arg.Status,
		arg.EstimatedReturn,
		arg.PlayerUrl,
		arg.RawJson,
	)
	return err
}
