// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type BankrollLedger struct {
	ID            int64              `json:"id"`
	EntryType     string             `json:"entry_type"`
	AmountCents   int64              `json:"amount_cents"`
	Currency      string             `json:"currency"`
	ReferenceType string             `json:"reference_type"`
	ReferenceID   string             `json:"reference_id"`
	Metadata      json.RawMessage    `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID           int64              `json:"id"`
	Source       string             `json:"source"`
	ExternalID   string             `json:"external_id"`
	Sport        string             `json:"sport"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	CommenceTime pgtype.Timestamptz `json:"commence_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type OddsHistory struct {
	ID                 int64              `json:"id"`
	GameID             int64              `json:"game_id"`
	Source             string             `json:"source"`
	BookKey            string             `json:"book_key"`
	BookName           string             `json:"book_name"`
	MarketKey          string             `json:"market_key"`
	MarketName         string             `json:"market_name"`
	OutcomeName        string             `json:"outcome_name"`
	OutcomeSide        string             `json:"outcome_side"`
	PriceAmerican      int32              `json:"price_american"`
	Point              *float64           `json:"point"`
	ImpliedProbability float64            `json:"implied_probability"`
	SnapshotHash       string             `json:"snapshot_hash"`
	RawJson            json.RawMessage    `json:"raw_json"`
	CapturedAt         pgtype.Timestamptz `json:"captured_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PollRun struct {
	ID            int64              `json:"id"`
	Source        string             `json:"source"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Status        string             `json:"status"`
	GamesSeen     int32              `json:"games_seen"`
	SnapshotsSeen int32              `json:"snapshots_seen"`
	InsertsCount  int32              `json:"inserts_count"`
	DedupSkips    int32              `json:"dedup_skips"`
	ErrorText     string             `json:"error_text"`
}
