// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type BankrollLedger struct {
	ID            int64              `json:"id"`
	EntryType     string             `json:"entry_type"`
	AmountCents   int64              `json:"amount_cents"`
	Currency      string             `json:"currency"`
	ReferenceType string             `json:"reference_type"`
	ReferenceID   string             `json:"reference_id"`
	Metadata      json.RawMessage    `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID           int64              `json:"id"`
	Source       string             `json:"source"`
	ExternalID   string             `json:"external_id"`
	Sport        string             `json:"sport"`
	HomeTeam     string             `json:"home_team"`
	AwayTeam     string             `json:"away_team"`
	CommenceTime pgtype.Timestamptz `json:"commence_time"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type GameWeatherSnapshot struct {
	ID                       int64              `json:"id"`
	GameID                   int64              `json:"game_id"`
	Source                   string             `json:"source"`
	ForecastTime             pgtype.Timestamptz `json:"forecast_time"`
	VenueName                string             `json:"venue_name"`
	VenueTimezone            string             `json:"venue_timezone"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	RoofType                 string             `json:"roof_type"`
	WeatherCode              *int32             `json:"weather_code"`
	TemperatureF             *float64           `json:"temperature_f"`
	ApparentTemperatureF     *float64           `json:"apparent_temperature_f"`
	PrecipitationProbability *float64           `json:"precipitation_probability"`
	PrecipitationInches      *float64           `json:"precipitation_inches"`
	WindSpeedMph             *float64           `json:"wind_speed_mph"`
	WindGustMph              *float64           `json:"wind_gust_mph"`
	WindDirectionDegrees     *int32             `json:"wind_direction_degrees"`
	RawJson                  json.RawMessage    `json:"raw_json"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type MlbPitcherStat struct {
	ID             int64              `json:"id"`
	Source         string             `json:"source"`
	ExternalID     string             `json:"external_id"`
	Season         int32              `json:"season"`
	SeasonType     string             `json:"season_type"`
	StatDate       pgtype.Date        `json:"stat_date"`
	PlayerName     string             `json:"player_name"`
	TeamExternalID string             `json:"team_external_id"`
	TeamName       string             `json:"team_name"`
	GamesStarted   int32              `json:"games_started"`
	InningsPitched *float64           `json:"innings_pitched"`
	Era            *float64           `json:"era"`
	Fip            *float64           `json:"fip"`
	Whip           *float64           `json:"whip"`
	StrikeoutRate  *float64           `json:"strikeout_rate"`
	WalkRate       *float64           `json:"walk_rate"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type MlbTeamStat struct {
	ID          int64              `json:"id"`
	Source      string             `json:"source"`
	ExternalID  string             `json:"external_id"`
	Season      int32              `json:"season"`
	SeasonType  string             `json:"season_type"`
	StatDate    pgtype.Date        `json:"stat_date"`
	TeamName    string             `json:"team_name"`
	GamesPlayed int32              `json:"games_played"`
	Wins        int32              `json:"wins"`
	Losses      int32              `json:"losses"`
	RunsScored  int32              `json:"runs_scored"`
	RunsAllowed int32              `json:"runs_allowed"`
	BattingOps  *float64           `json:"batting_ops"`
	TeamEra     *float64           `json:"team_era"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ModelPrediction struct {
	ID                   int64              `json:"id"`
	GameID               int64              `json:"game_id"`
	Source               string             `json:"source"`
	Sport                string             `json:"sport"`
	BookKey              string             `json:"book_key"`
	MarketKey            string             `json:"market_key"`
	ModelFamily          string             `json:"model_family"`
	ModelVersion         string             `json:"model_version"`
	ManifestVersion      string             `json:"manifest_version"`
	FeatureVector        []float64          `json:"feature_vector"`
	PredictedProbability float64            `json:"predicted_probability"`
	MarketProbability    float64            `json:"market_probability"`
	ClosingProbability   *float64           `json:"closing_probability"`
	EventTime            pgtype.Timestamptz `json:"event_time"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type NbaTeamStat struct {
	ID              int64              `json:"id"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Season          int32              `json:"season"`
	SeasonType      string             `json:"season_type"`
	StatDate        pgtype.Date        `json:"stat_date"`
	TeamName        string             `json:"team_name"`
	GamesPlayed     int32              `json:"games_played"`
	Wins            int32              `json:"wins"`
	Losses          int32              `json:"losses"`
	OffensiveRating *float64           `json:"offensive_rating"`
	DefensiveRating *float64           `json:"defensive_rating"`
	NetRating       *float64           `json:"net_rating"`
	Pace            *float64           `json:"pace"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type NflQbStat struct {
	ID                   int64              `json:"id"`
	Source               string             `json:"source"`
	ExternalID           string             `json:"external_id"`
	Season               int32              `json:"season"`
	SeasonType           string             `json:"season_type"`
	StatDate             pgtype.Date        `json:"stat_date"`
	PlayerName           string             `json:"player_name"`
	TeamExternalID       string             `json:"team_external_id"`
	TeamName             string             `json:"team_name"`
	GamesPlayed          int32              `json:"games_played"`
	PassAttempts         int32              `json:"pass_attempts"`
	CompletionPercentage *float64           `json:"completion_percentage"`
	YardsPerAttempt      *float64           `json:"yards_per_attempt"`
	EpaPerPlay           *float64           `json:"epa_per_play"`
	SuccessRate          *float64           `json:"success_rate"`
	Cpoe                 *float64           `json:"cpoe"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type NflTeamStat struct {
	ID                   int64              `json:"id"`
	Source               string             `json:"source"`
	ExternalID           string             `json:"external_id"`
	Season               int32              `json:"season"`
	SeasonType           string             `json:"season_type"`
	StatDate             pgtype.Date        `json:"stat_date"`
	TeamName             string             `json:"team_name"`
	GamesPlayed          int32              `json:"games_played"`
	Wins                 int32              `json:"wins"`
	Losses               int32              `json:"losses"`
	Ties                 int32              `json:"ties"`
	PointsFor            int32              `json:"points_for"`
	PointsAgainst        int32              `json:"points_against"`
	OffensiveEpaPerPlay  *float64           `json:"offensive_epa_per_play"`
	DefensiveEpaPerPlay  *float64           `json:"defensive_epa_per_play"`
	OffensiveSuccessRate *float64           `json:"offensive_success_rate"`
	DefensiveSuccessRate *float64           `json:"defensive_success_rate"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type NhlGoalieStat struct {
	ID                      int64              `json:"id"`
	Source                  string             `json:"source"`
	ExternalID              string             `json:"external_id"`
	Season                  int32              `json:"season"`
	SeasonType              string             `json:"season_type"`
	StatDate                pgtype.Date        `json:"stat_date"`
	PlayerName              string             `json:"player_name"`
	TeamExternalID          string             `json:"team_external_id"`
	TeamName                string             `json:"team_name"`
	GamesPlayed             int32              `json:"games_played"`
	Starts                  int32              `json:"starts"`
	MinutesPlayed           *int32             `json:"minutes_played"`
	SavePercentage          *float64           `json:"save_percentage"`
	GoalsAgainstAverage     *float64           `json:"goals_against_average"`
	GoalsSavedAboveExpected *float64           `json:"goals_saved_above_expected"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type NhlTeamStat struct {
	ID                  int64              `json:"id"`
	Source              string             `json:"source"`
	ExternalID          string             `json:"external_id"`
	Season              int32              `json:"season"`
	SeasonType          string             `json:"season_type"`
	StatDate            pgtype.Date        `json:"stat_date"`
	TeamName            string             `json:"team_name"`
	GamesPlayed         int32              `json:"games_played"`
	Wins                int32              `json:"wins"`
	Losses              int32              `json:"losses"`
	OtLosses            int32              `json:"ot_losses"`
	GoalsForPerGame     *float64           `json:"goals_for_per_game"`
	GoalsAgainstPerGame *float64           `json:"goals_against_per_game"`
	ExpectedGoalsShare  *float64           `json:"expected_goals_share"`
	SavePercentage      *float64           `json:"save_percentage"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type OddsHistory struct {
	ID                 int64              `json:"id"`
	GameID             int64              `json:"game_id"`
	Source             string             `json:"source"`
	BookKey            string             `json:"book_key"`
	BookName           string             `json:"book_name"`
	MarketKey          string             `json:"market_key"`
	MarketName         string             `json:"market_name"`
	OutcomeName        string             `json:"outcome_name"`
	OutcomeSide        string             `json:"outcome_side"`
	PriceAmerican      int32              `json:"price_american"`
	Point              *float64           `json:"point"`
	ImpliedProbability float64            `json:"implied_probability"`
	SnapshotHash       string             `json:"snapshot_hash"`
	RawJson            json.RawMessage    `json:"raw_json"`
	CapturedAt         pgtype.Timestamptz `json:"captured_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type PlayerInjuryReport struct {
	ID              int64              `json:"id"`
	Source          string             `json:"source"`
	Sport           string             `json:"sport"`
	ReportDate      pgtype.Date        `json:"report_date"`
	ExternalID      string             `json:"external_id"`
	PlayerName      string             `json:"player_name"`
	TeamExternalID  string             `json:"team_external_id"`
	Position        string             `json:"position"`
	Injury          string             `json:"injury"`
	Status          string             `json:"status"`
	EstimatedReturn *string            `json:"estimated_return"`
	PlayerUrl       string             `json:"player_url"`
	RawJson         json.RawMessage    `json:"raw_json"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type PollRun struct {
	ID            int64              `json:"id"`
	Source        string             `json:"source"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Status        string             `json:"status"`
	GamesSeen     int32              `json:"games_seen"`
	SnapshotsSeen int32              `json:"snapshots_seen"`
	InsertsCount  int32              `json:"inserts_count"`
	DedupSkips    int32              `json:"dedup_skips"`
	ErrorText     string             `json:"error_text"`
}

type RecommendationSnapshot struct {
	ID                     int64              `json:"id"`
	GeneratedAt            pgtype.Timestamptz `json:"generated_at"`
	Sport                  string             `json:"sport"`
	GameID                 int64              `json:"game_id"`
	EventTime              pgtype.Timestamptz `json:"event_time"`
	EventDate              pgtype.Date        `json:"event_date"`
	MarketKey              string             `json:"market_key"`
	RecommendedSide        string             `json:"recommended_side"`
	BestBook               string             `json:"best_book"`
	BestAmericanOdds       int32              `json:"best_american_odds"`
	ModelProbability       float64            `json:"model_probability"`
	MarketProbability      float64            `json:"market_probability"`
	Edge                   float64            `json:"edge"`
	SuggestedStakeFraction float64            `json:"suggested_stake_fraction"`
	SuggestedStakeCents    int64              `json:"suggested_stake_cents"`
	BankrollCheckPass      bool               `json:"bankroll_check_pass"`
	BankrollCheckReason    string             `json:"bankroll_check_reason"`
	RankScore              float64            `json:"rank_score"`
	Metadata               json.RawMessage    `json:"metadata"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
}
