// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: moneypuck.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMoneypuckGoalieGames = `-- name: CountMoneypuckGoalieGames :one
SELECT COUNT(*)::BIGINT FROM moneypuck_goalie_games
`

func (q *Queries) CountMoneypuckGoalieGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMoneypuckGoalieGames)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMoneypuckTeamGames = `-- name: CountMoneypuckTeamGames :one
SELECT COUNT(*)::BIGINT FROM moneypuck_team_games
`

func (q *Queries) CountMoneypuckTeamGames(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMoneypuckTeamGames)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getGameResult = `-- name: GetGameResult :many
SELECT
    team, opponent, home_or_away, goals_for, goals_against
FROM moneypuck_team_games
WHERE game_id = $1
  AND situation = 'all'
ORDER BY home_or_away ASC
`

type GetGameResultRow struct {
	Team         string   `json:"team"`
	Opponent     string   `json:"opponent"`
	HomeOrAway   string   `json:"home_or_away"`
	GoalsFor     *float64 `json:"goals_for"`
	GoalsAgainst *float64 `json:"goals_against"`
}

// Returns goals for/against from the "all" situation for both teams in a game.
// Two rows returned: one per team, with home_or_away indicating side.
func (q *Queries) GetGameResult(ctx context.Context, gameID string) ([]GetGameResultRow, error) {
	rows, err := q.db.Query(ctx, getGameResult, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGameResultRow
	for rows.Next() {
		var i GetGameResultRow
		if err := rows.Scan(
			&i.Team,
			&i.Opponent,
			&i.HomeOrAway,
			&i.GoalsFor,
			&i.GoalsAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGoalieSeasonGSAx = `-- name: GetGoalieSeasonGSAx :one
SELECT
    COALESCE(SUM(gsax), 0)::DOUBLE PRECISION AS cumulative_gsax,
    COALESCE(SUM(icetime), 0)::DOUBLE PRECISION AS cumulative_icetime,
    COUNT(*)::BIGINT AS games_played
FROM moneypuck_goalie_games
WHERE player_id = $1
  AND season = $2
  AND situation = '5on5'
  AND game_date < $3
`

type GetGoalieSeasonGSAxParams struct {
	PlayerID string      `json:"player_id"`
	Season   int32       `json:"season"`
	GameDate pgtype.Date `json:"game_date"`
}

type GetGoalieSeasonGSAxRow struct {
	CumulativeGsax    float64 `json:"cumulative_gsax"`
	CumulativeIcetime float64 `json:"cumulative_icetime"`
	GamesPlayed       int64   `json:"games_played"`
}

// Returns cumulative 5on5 GSAx for a goalie in a season before a given date.
func (q *Queries) GetGoalieSeasonGSAx(ctx context.Context, arg GetGoalieSeasonGSAxParams) (GetGoalieSeasonGSAxRow, error) {
	row := q.db.QueryRow(ctx, getGoalieSeasonGSAx, arg.PlayerID, arg.Season, arg.GameDate)
	var i GetGoalieSeasonGSAxRow
	err := row.Scan(&i.CumulativeGsax, &i.CumulativeIcetime, &i.GamesPlayed)
	return i, err
}

const getStartingGoalie = `-- name: GetStartingGoalie :one
SELECT
    player_id, name, team, icetime, xgoals, goals, gsax,
    high_danger_xgoals, high_danger_goals
FROM moneypuck_goalie_games
WHERE game_id = $1
  AND team = $2
  AND situation = '5on5'
ORDER BY icetime DESC
LIMIT 1
`

type GetStartingGoalieParams struct {
	GameID string `json:"game_id"`
	Team   string `json:"team"`
}

type GetStartingGoalieRow struct {
	PlayerID         string   `json:"player_id"`
	Name             string   `json:"name"`
	Team             string   `json:"team"`
	Icetime          *float64 `json:"icetime"`
	Xgoals           *float64 `json:"xgoals"`
	Goals            *float64 `json:"goals"`
	Gsax             *float64 `json:"gsax"`
	HighDangerXgoals *float64 `json:"high_danger_xgoals"`
	HighDangerGoals  *float64 `json:"high_danger_goals"`
}

// Returns the goalie with the most 5on5 icetime for a team in a given game.
func (q *Queries) GetStartingGoalie(ctx context.Context, arg GetStartingGoalieParams) (GetStartingGoalieRow, error) {
	row := q.db.QueryRow(ctx, getStartingGoalie, arg.GameID, arg.Team)
	var i GetStartingGoalieRow
	err := row.Scan(
		&i.PlayerID,
		&i.Name,
		&i.Team,
		&i.Icetime,
		&i.Xgoals,
		&i.Goals,
		&i.Gsax,
		&i.HighDangerXgoals,
		&i.HighDangerGoals,
	)
	return i, err
}

const getTeamRolling5on5Stats = `-- name: GetTeamRolling5on5Stats :many
SELECT
    game_id, game_date, opponent, home_or_away,
    xgoals_percentage, xgoals_for, xgoals_against,
    score_venue_adjusted_xgoals_for, score_venue_adjusted_xgoals_against,
    corsi_percentage, fenwick_percentage,
    shots_on_goal_for, shots_on_goal_against,
    shot_attempts_for, shot_attempts_against,
    high_danger_shots_for, high_danger_shots_against,
    high_danger_xgoals_for, high_danger_xgoals_against,
    goals_for, goals_against
FROM moneypuck_team_games
WHERE team = $1
  AND situation = '5on5'
  AND game_date < $2
  AND season = $3
  AND is_playoff = FALSE
ORDER BY game_date DESC
LIMIT $4
`

type GetTeamRolling5on5StatsParams struct {
	Team     string      `json:"team"`
	GameDate pgtype.Date `json:"game_date"`
	Season   int32       `json:"season"`
	Limit    int32       `json:"limit"`
}

type GetTeamRolling5on5StatsRow struct {
	GameID                          string      `json:"game_id"`
	GameDate                        pgtype.Date `json:"game_date"`
	Opponent                        string      `json:"opponent"`
	HomeOrAway                      string      `json:"home_or_away"`
	XgoalsPercentage                *float64    `json:"xgoals_percentage"`
	XgoalsFor                       *float64    `json:"xgoals_for"`
	XgoalsAgainst                   *float64    `json:"xgoals_against"`
	ScoreVenueAdjustedXgoalsFor     *float64    `json:"score_venue_adjusted_xgoals_for"`
	ScoreVenueAdjustedXgoalsAgainst *float64    `json:"score_venue_adjusted_xgoals_against"`
	CorsiPercentage                 *float64    `json:"corsi_percentage"`
	FenwickPercentage               *float64    `json:"fenwick_percentage"`
	ShotsOnGoalFor                  *float64    `json:"shots_on_goal_for"`
	ShotsOnGoalAgainst              *float64    `json:"shots_on_goal_against"`
	ShotAttemptsFor                 *float64    `json:"shot_attempts_for"`
	ShotAttemptsAgainst             *float64    `json:"shot_attempts_against"`
	HighDangerShotsFor              *float64    `json:"high_danger_shots_for"`
	HighDangerShotsAgainst          *float64    `json:"high_danger_shots_against"`
	HighDangerXgoalsFor             *float64    `json:"high_danger_xgoals_for"`
	HighDangerXgoalsAgainst         *float64    `json:"high_danger_xgoals_against"`
	GoalsFor                        *float64    `json:"goals_for"`
	GoalsAgainst                    *float64    `json:"goals_against"`
}

// Returns the last N 5on5 games for a team strictly before a given date, ordered newest first.
// The caller computes rolling averages from these rows.
func (q *Queries) GetTeamRolling5on5Stats(ctx context.Context, arg GetTeamRolling5on5StatsParams) ([]GetTeamRolling5on5StatsRow, error) {
	rows, err := q.db.Query(ctx, getTeamRolling5on5Stats,
		arg.Team,
		arg.GameDate,
		arg.Season,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamRolling5on5StatsRow
	for rows.Next() {
		var i GetTeamRolling5on5StatsRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameDate,
			&i.Opponent,
			&i.HomeOrAway,
			&i.XgoalsPercentage,
			&i.XgoalsFor,
			&i.XgoalsAgainst,
			&i.ScoreVenueAdjustedXgoalsFor,
			&i.ScoreVenueAdjustedXgoalsAgainst,
			&i.CorsiPercentage,
			&i.FenwickPercentage,
			&i.ShotsOnGoalFor,
			&i.ShotsOnGoalAgainst,
			&i.ShotAttemptsFor,
			&i.ShotAttemptsAgainst,
			&i.HighDangerShotsFor,
			&i.HighDangerShotsAgainst,
			&i.HighDangerXgoalsFor,
			&i.HighDangerXgoalsAgainst,
			&i.GoalsFor,
			&i.GoalsAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonGameDates = `-- name: ListSeasonGameDates :many
SELECT DISTINCT game_date
FROM moneypuck_team_games
WHERE season = $1
  AND situation = 'all'
  AND is_playoff = FALSE
ORDER BY game_date ASC
`

// Returns distinct game dates for a season (for odds backfill targeting).
func (q *Queries) ListSeasonGameDates(ctx context.Context, season int32) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listSeasonGameDates, season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Date
	for rows.Next() {
		var game_date pgtype.Date
		if err := rows.Scan(&game_date); err != nil {
			return nil, err
		}
		items = append(items, game_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeasonTeamGames = `-- name: ListSeasonTeamGames :many
SELECT
    game_id, game_date, opponent, home_or_away, goals_for, goals_against
FROM moneypuck_team_games
WHERE team = $1
  AND season = $2
  AND situation = 'all'
  AND is_playoff = FALSE
ORDER BY game_date ASC
`

type ListSeasonTeamGamesParams struct {
	Team   string `json:"team"`
	Season int32  `json:"season"`
}

type ListSeasonTeamGamesRow struct {
	GameID       string      `json:"game_id"`
	GameDate     pgtype.Date `json:"game_date"`
	Opponent     string      `json:"opponent"`
	HomeOrAway   string      `json:"home_or_away"`
	GoalsFor     *float64    `json:"goals_for"`
	GoalsAgainst *float64    `json:"goals_against"`
}

// Returns all games for a team in a season (all situation), ordered by date.
func (q *Queries) ListSeasonTeamGames(ctx context.Context, arg ListSeasonTeamGamesParams) ([]ListSeasonTeamGamesRow, error) {
	rows, err := q.db.Query(ctx, listSeasonTeamGames, arg.Team, arg.Season)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSeasonTeamGamesRow
	for rows.Next() {
		var i ListSeasonTeamGamesRow
		if err := rows.Scan(
			&i.GameID,
			&i.GameDate,
			&i.Opponent,
			&i.HomeOrAway,
			&i.GoalsFor,
			&i.GoalsAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMoneypuckGoalieGame = `-- name: UpsertMoneypuckGoalieGame :exec
INSERT INTO moneypuck_goalie_games (
    season, game_id, player_id, name, team, opponent, home_or_away, game_date, situation,
    icetime, xgoals, goals, gsax, shots_against, high_danger_xgoals, high_danger_goals
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (game_id, player_id, situation) DO UPDATE SET
    season = EXCLUDED.season,
    name = EXCLUDED.name,
    team = EXCLUDED.team,
    opponent = EXCLUDED.opponent,
    home_or_away = EXCLUDED.home_or_away,
    game_date = EXCLUDED.game_date,
    icetime = EXCLUDED.icetime,
    xgoals = EXCLUDED.xgoals,
    goals = EXCLUDED.goals,
    gsax = EXCLUDED.gsax,
    shots_against = EXCLUDED.shots_against,
    high_danger_xgoals = EXCLUDED.high_danger_xgoals,
    high_danger_goals = EXCLUDED.high_danger_goals
`

type UpsertMoneypuckGoalieGameParams struct {
	Season           int32       `json:"season"`
	GameID           string      `json:"game_id"`
	PlayerID         string      `json:"player_id"`
	Name             string      `json:"name"`
	Team             string      `json:"team"`
	Opponent         string      `json:"opponent"`
	HomeOrAway       string      `json:"home_or_away"`
	GameDate         pgtype.Date `json:"game_date"`
	Situation        string      `json:"situation"`
	Icetime          *float64    `json:"icetime"`
	Xgoals           *float64    `json:"xgoals"`
	Goals            *float64    `json:"goals"`
	Gsax             *float64    `json:"gsax"`
	ShotsAgainst     *float64    `json:"shots_against"`
	HighDangerXgoals *float64    `json:"high_danger_xgoals"`
	HighDangerGoals  *float64    `json:"high_danger_goals"`
}

func (q *Queries) UpsertMoneypuckGoalieGame(ctx context.Context, arg UpsertMoneypuckGoalieGameParams) error {
	_, err := q.db.Exec(ctx, upsertMoneypuckGoalieGame,
		arg.Season,
		arg.GameID,
		arg.PlayerID,
		arg.Name,
		arg.Team,
		arg.Opponent,
		arg.HomeOrAway,
		arg.GameDate,
		arg.Situation,
		arg.Icetime,
		arg.Xgoals,
		arg.Goals,
		arg.Gsax,
		arg.ShotsAgainst,
		arg.HighDangerXgoals,
		arg.HighDangerGoals,
	)
	return err
}

const upsertMoneypuckTeamGame = `-- name: UpsertMoneypuckTeamGame :exec
INSERT INTO moneypuck_team_games (
    season, game_id, team, opponent, home_or_away, game_date, situation, is_playoff,
    xgoals_percentage, xgoals_for, xgoals_against,
    score_venue_adjusted_xgoals_for, score_venue_adjusted_xgoals_against,
    corsi_percentage, fenwick_percentage,
    shots_on_goal_for, shots_on_goal_against,
    shot_attempts_for, shot_attempts_against,
    high_danger_shots_for, high_danger_shots_against,
    high_danger_xgoals_for, high_danger_xgoals_against,
    goals_for, goals_against
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25
)
ON CONFLICT (game_id, team, situation) DO UPDATE SET
    season = EXCLUDED.season,
    opponent = EXCLUDED.opponent,
    home_or_away = EXCLUDED.home_or_away,
    game_date = EXCLUDED.game_date,
    is_playoff = EXCLUDED.is_playoff,
    xgoals_percentage = EXCLUDED.xgoals_percentage,
    xgoals_for = EXCLUDED.xgoals_for,
    xgoals_against = EXCLUDED.xgoals_against,
    score_venue_adjusted_xgoals_for = EXCLUDED.score_venue_adjusted_xgoals_for,
    score_venue_adjusted_xgoals_against = EXCLUDED.score_venue_adjusted_xgoals_against,
    corsi_percentage = EXCLUDED.corsi_percentage,
    fenwick_percentage = EXCLUDED.fenwick_percentage,
    shots_on_goal_for = EXCLUDED.shots_on_goal_for,
    shots_on_goal_against = EXCLUDED.shots_on_goal_against,
    shot_attempts_for = EXCLUDED.shot_attempts_for,
    shot_attempts_against = EXCLUDED.shot_attempts_against,
    high_danger_shots_for = EXCLUDED.high_danger_shots_for,
    high_danger_shots_against = EXCLUDED.high_danger_shots_against,
    high_danger_xgoals_for = EXCLUDED.high_danger_xgoals_for,
    high_danger_xgoals_against = EXCLUDED.high_danger_xgoals_against,
    goals_for = EXCLUDED.goals_for,
    goals_against = EXCLUDED.goals_against
`

type UpsertMoneypuckTeamGameParams struct {
	Season                          int32       `json:"season"`
	GameID                          string      `json:"game_id"`
	Team                            string      `json:"team"`
	Opponent                        string      `json:"opponent"`
	HomeOrAway                      string      `json:"home_or_away"`
	GameDate                        pgtype.Date `json:"game_date"`
	Situation                       string      `json:"situation"`
	IsPlayoff                       bool        `json:"is_playoff"`
	XgoalsPercentage                *float64    `json:"xgoals_percentage"`
	XgoalsFor                       *float64    `json:"xgoals_for"`
	XgoalsAgainst                   *float64    `json:"xgoals_against"`
	ScoreVenueAdjustedXgoalsFor     *float64    `json:"score_venue_adjusted_xgoals_for"`
	ScoreVenueAdjustedXgoalsAgainst *float64    `json:"score_venue_adjusted_xgoals_against"`
	CorsiPercentage                 *float64    `json:"corsi_percentage"`
	FenwickPercentage               *float64    `json:"fenwick_percentage"`
	ShotsOnGoalFor                  *float64    `json:"shots_on_goal_for"`
	ShotsOnGoalAgainst              *float64    `json:"shots_on_goal_against"`
	ShotAttemptsFor                 *float64    `json:"shot_attempts_for"`
	ShotAttemptsAgainst             *float64    `json:"shot_attempts_against"`
	HighDangerShotsFor              *float64    `json:"high_danger_shots_for"`
	HighDangerShotsAgainst          *float64    `json:"high_danger_shots_against"`
	HighDangerXgoalsFor             *float64    `json:"high_danger_xgoals_for"`
	HighDangerXgoalsAgainst         *float64    `json:"high_danger_xgoals_against"`
	GoalsFor                        *float64    `json:"goals_for"`
	GoalsAgainst                    *float64    `json:"goals_against"`
}

func (q *Queries) UpsertMoneypuckTeamGame(ctx context.Context, arg UpsertMoneypuckTeamGameParams) error {
	_, err := q.db.Exec(ctx, upsertMoneypuckTeamGame,
		arg.Season,
		arg.GameID,
		arg.Team,
		arg.Opponent,
		arg.HomeOrAway,
		arg.GameDate,
		arg.Situation,
		arg.IsPlayoff,
		arg.XgoalsPercentage,
		arg.XgoalsFor,
		arg.XgoalsAgainst,
		arg.ScoreVenueAdjustedXgoalsFor,
		arg.ScoreVenueAdjustedXgoalsAgainst,
		arg.CorsiPercentage,
		arg.FenwickPercentage,
		arg.ShotsOnGoalFor,
		arg.ShotsOnGoalAgainst,
		arg.ShotAttemptsFor,
		arg.ShotAttemptsAgainst,
		arg.HighDangerShotsFor,
		arg.HighDangerShotsAgainst,
		arg.HighDangerXgoalsFor,
		arg.HighDangerXgoalsAgainst,
		arg.GoalsFor,
		arg.GoalsAgainst,
	)
	return err
}
