// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: odds_history.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOddsHistoryRows = `-- name: CountOddsHistoryRows :one
SELECT COUNT(*)::BIGINT
FROM odds_history
`

func (q *Queries) CountOddsHistoryRows(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOddsHistoryRows)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestMarketProbabilityForGame = `-- name: GetLatestMarketProbabilityForGame :one
SELECT implied_probability
FROM odds_history
WHERE game_id = $1
  AND market_key = 'h2h'
  AND outcome_side = 'home'
ORDER BY captured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMarketProbabilityForGame(ctx context.Context, gameID int64) (float64, error) {
	row := q.db.QueryRow(ctx, getLatestMarketProbabilityForGame, gameID)
	var implied_probability float64
	err := row.Scan(&implied_probability)
	return implied_probability, err
}

const getLatestSnapshotHash = `-- name: GetLatestSnapshotHash :one
SELECT snapshot_hash
FROM odds_history
WHERE game_id = $1
  AND source = $2
  AND book_key = $3
  AND market_key = $4
  AND outcome_name = $5
  AND outcome_side = $6
  AND point IS NOT DISTINCT FROM $7
ORDER BY captured_at DESC
LIMIT 1
`

type GetLatestSnapshotHashParams struct {
	GameID      int64    `json:"game_id"`
	Source      string   `json:"source"`
	BookKey     string   `json:"book_key"`
	MarketKey   string   `json:"market_key"`
	OutcomeName string   `json:"outcome_name"`
	OutcomeSide string   `json:"outcome_side"`
	Point       *float64 `json:"point"`
}

func (q *Queries) GetLatestSnapshotHash(ctx context.Context, arg GetLatestSnapshotHashParams) (string, error) {
	row := q.db.QueryRow(ctx, getLatestSnapshotHash,
		arg.GameID,
		arg.Source,
		arg.BookKey,
		arg.MarketKey,
		arg.OutcomeName,
		arg.OutcomeSide,
		arg.Point,
	)
	var snapshot_hash string
	err := row.Scan(&snapshot_hash)
	return snapshot_hash, err
}

const insertOddsSnapshot = `-- name: InsertOddsSnapshot :one
INSERT INTO odds_history (
    game_id,
    source,
    book_key,
    book_name,
    market_key,
    market_name,
    outcome_name,
    outcome_side,
    price_american,
    point,
    implied_probability,
    snapshot_hash,
    raw_json,
    captured_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, game_id, source, book_key, book_name, market_key, market_name, outcome_name, outcome_side, price_american, point, implied_probability, snapshot_hash, raw_json, captured_at, created_at
`

type InsertOddsSnapshotParams struct {
	GameID             int64              `json:"game_id"`
	Source             string             `json:"source"`
	BookKey            string             `json:"book_key"`
	BookName           string             `json:"book_name"`
	MarketKey          string             `json:"market_key"`
	MarketName         string             `json:"market_name"`
	OutcomeName        string             `json:"outcome_name"`
	OutcomeSide        string             `json:"outcome_side"`
	PriceAmerican      int32              `json:"price_american"`
	Point              *float64           `json:"point"`
	ImpliedProbability float64            `json:"implied_probability"`
	SnapshotHash       string             `json:"snapshot_hash"`
	RawJson            json.RawMessage    `json:"raw_json"`
	CapturedAt         pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) InsertOddsSnapshot(ctx context.Context, arg InsertOddsSnapshotParams) (OddsHistory, error) {
	row := q.db.QueryRow(ctx, insertOddsSnapshot,
		arg.GameID,
		arg.Source,
		arg.BookKey,
		arg.BookName,
		arg.MarketKey,
		arg.MarketName,
		arg.OutcomeName,
		arg.OutcomeSide,
		arg.PriceAmerican,
		arg.Point,
		arg.ImpliedProbability,
		arg.SnapshotHash,
		arg.RawJson,
		arg.CapturedAt,
	)
	var i OddsHistory
	err := row.Scan(
		&i.ID,
		&i.GameID,
		&i.Source,
		&i.BookKey,
		&i.BookName,
		&i.MarketKey,
		&i.MarketName,
		&i.OutcomeName,
		&i.OutcomeSide,
		&i.PriceAmerican,
		&i.Point,
		&i.ImpliedProbability,
		&i.SnapshotHash,
		&i.RawJson,
		&i.CapturedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestOdds = `-- name: ListLatestOdds :many
WITH latest AS (
    SELECT DISTINCT ON (
        oh.game_id,
        oh.book_key,
        oh.market_key,
        oh.outcome_name,
        oh.outcome_side,
        oh.point
    )
        oh.game_id,
        oh.book_key,
        oh.book_name,
        oh.market_key,
        oh.market_name,
        oh.outcome_name,
        oh.outcome_side,
        oh.price_american,
        oh.point,
        oh.implied_probability,
        oh.captured_at
    FROM odds_history AS oh
    ORDER BY
        oh.game_id,
        oh.book_key,
        oh.market_key,
        oh.outcome_name,
        oh.outcome_side,
        oh.point,
        oh.captured_at DESC
)
SELECT
    latest.game_id,
    g.sport,
    g.home_team,
    g.away_team,
    g.commence_time,
    latest.book_key,
    latest.book_name,
    latest.market_key,
    latest.market_name,
    latest.outcome_name,
    latest.outcome_side,
    latest.price_american,
    latest.point,
    latest.implied_probability,
    latest.captured_at
FROM latest
JOIN games AS g ON g.id = latest.game_id
WHERE
    $1::text IS NULL
    OR g.sport = $1::text
ORDER BY
    g.commence_time ASC,
    latest.book_key ASC,
    latest.market_key ASC,
    latest.outcome_name ASC
LIMIT $2
`

type ListLatestOddsParams struct {
	Sport    *string `json:"sport"`
	RowLimit int32   `json:"row_limit"`
}

type ListLatestOddsRow struct {
	GameID             int64              `json:"game_id"`
	Sport              string             `json:"sport"`
	HomeTeam           string             `json:"home_team"`
	AwayTeam           string             `json:"away_team"`
	CommenceTime       pgtype.Timestamptz `json:"commence_time"`
	BookKey            string             `json:"book_key"`
	BookName           string             `json:"book_name"`
	MarketKey          string             `json:"market_key"`
	MarketName         string             `json:"market_name"`
	OutcomeName        string             `json:"outcome_name"`
	OutcomeSide        string             `json:"outcome_side"`
	PriceAmerican      int32              `json:"price_american"`
	Point              *float64           `json:"point"`
	ImpliedProbability float64            `json:"implied_probability"`
	CapturedAt         pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) ListLatestOdds(ctx context.Context, arg ListLatestOddsParams) ([]ListLatestOddsRow, error) {
	rows, err := q.db.Query(ctx, listLatestOdds, arg.Sport, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestOddsRow
	for rows.Next() {
		var i ListLatestOddsRow
		if err := rows.Scan(
			&i.GameID,
			&i.Sport,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.CommenceTime,
			&i.BookKey,
			&i.BookName,
			&i.MarketKey,
			&i.MarketName,
			&i.OutcomeName,
			&i.OutcomeSide,
			&i.PriceAmerican,
			&i.Point,
			&i.ImpliedProbability,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestOddsForUpcoming = `-- name: ListLatestOddsForUpcoming :many
WITH latest AS (
    SELECT DISTINCT ON (
        oh.game_id,
        oh.book_key,
        oh.market_key,
        oh.outcome_name,
        oh.outcome_side,
        oh.point
    )
        oh.game_id,
        oh.book_key,
        oh.book_name,
        oh.market_key,
        oh.market_name,
        oh.outcome_name,
        oh.outcome_side,
        oh.price_american,
        oh.point,
        oh.implied_probability,
        oh.captured_at
    FROM odds_history AS oh
    JOIN games AS g ON g.id = oh.game_id
    WHERE g.commence_time > NOW() - INTERVAL '12 hours'
      AND (
          $2::text IS NULL
          OR g.sport = $2::text
      )
    ORDER BY
        oh.game_id,
        oh.book_key,
        oh.market_key,
        oh.outcome_name,
        oh.outcome_side,
        oh.point,
        oh.captured_at DESC
)
SELECT
    latest.game_id,
    g.sport,
    g.home_team,
    g.away_team,
    g.commence_time,
    latest.book_key,
    latest.book_name,
    latest.market_key,
    latest.market_name,
    latest.outcome_name,
    latest.outcome_side,
    latest.price_american,
    latest.point,
    latest.implied_probability,
    latest.captured_at
FROM latest
JOIN games AS g ON g.id = latest.game_id
ORDER BY
    g.commence_time ASC,
    latest.book_key ASC,
    latest.market_key ASC,
    latest.outcome_name ASC
LIMIT $1
`

type ListLatestOddsForUpcomingParams struct {
	RowLimit int32   `json:"row_limit"`
	Sport    *string `json:"sport"`
}

type ListLatestOddsForUpcomingRow struct {
	GameID             int64              `json:"game_id"`
	Sport              string             `json:"sport"`
	HomeTeam           string             `json:"home_team"`
	AwayTeam           string             `json:"away_team"`
	CommenceTime       pgtype.Timestamptz `json:"commence_time"`
	BookKey            string             `json:"book_key"`
	BookName           string             `json:"book_name"`
	MarketKey          string             `json:"market_key"`
	MarketName         string             `json:"market_name"`
	OutcomeName        string             `json:"outcome_name"`
	OutcomeSide        string             `json:"outcome_side"`
	PriceAmerican      int32              `json:"price_american"`
	Point              *float64           `json:"point"`
	ImpliedProbability float64            `json:"implied_probability"`
	CapturedAt         pgtype.Timestamptz `json:"captured_at"`
}

func (q *Queries) ListLatestOddsForUpcoming(ctx context.Context, arg ListLatestOddsForUpcomingParams) ([]ListLatestOddsForUpcomingRow, error) {
	rows, err := q.db.Query(ctx, listLatestOddsForUpcoming, arg.RowLimit, arg.Sport)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestOddsForUpcomingRow
	for rows.Next() {
		var i ListLatestOddsForUpcomingRow
		if err := rows.Scan(
			&i.GameID,
			&i.Sport,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.CommenceTime,
			&i.BookKey,
			&i.BookName,
			&i.MarketKey,
			&i.MarketName,
			&i.OutcomeName,
			&i.OutcomeSide,
			&i.PriceAmerican,
			&i.Point,
			&i.ImpliedProbability,
			&i.CapturedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
