// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CompletePollRun(ctx context.Context, arg CompletePollRunParams) error
	CountOddsHistoryRows(ctx context.Context) (int64, error)
	GetBankrollBalanceCents(ctx context.Context) (int64, error)
	GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error)
	GetLatestPollRun(ctx context.Context) (PollRun, error)
	GetLatestSnapshotHash(ctx context.Context, arg GetLatestSnapshotHashParams) (string, error)
	InsertBankrollEntry(ctx context.Context, arg InsertBankrollEntryParams) (BankrollLedger, error)
	InsertOddsSnapshot(ctx context.Context, arg InsertOddsSnapshotParams) (OddsHistory, error)
	InsertPollRun(ctx context.Context, arg InsertPollRunParams) (PollRun, error)
	ListLatestOdds(ctx context.Context, limit int32) ([]ListLatestOddsRow, error)
	ListUpcomingGames(ctx context.Context, limit int32) ([]Game, error)
	UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error)
	UpsertMLBPitcherStats(ctx context.Context, arg UpsertMLBPitcherStatsParams) error
	UpsertMLBTeamStats(ctx context.Context, arg UpsertMLBTeamStatsParams) error
	UpsertNBATeamStats(ctx context.Context, arg UpsertNBATeamStatsParams) error
}

var _ Querier = (*Queries)(nil)
