// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CompletePollRun(ctx context.Context, arg CompletePollRunParams) error
	CountModelPredictions(ctx context.Context) (int64, error)
	CountOddsHistoryRows(ctx context.Context) (int64, error)
	GetBankrollBalanceCents(ctx context.Context) (int64, error)
	GetDashboardSummary(ctx context.Context) (GetDashboardSummaryRow, error)
	GetLatestPollRun(ctx context.Context) (PollRun, error)
	GetLatestSnapshotHash(ctx context.Context, arg GetLatestSnapshotHashParams) (string, error)
	GetOddsArchiveSummary(ctx context.Context, sport *string) (GetOddsArchiveSummaryRow, error)
	InsertBankrollEntry(ctx context.Context, arg InsertBankrollEntryParams) (BankrollLedger, error)
	InsertOddsSnapshot(ctx context.Context, arg InsertOddsSnapshotParams) (OddsHistory, error)
	InsertPollRun(ctx context.Context, arg InsertPollRunParams) (PollRun, error)
	InsertRecommendationOutcomeIfChanged(ctx context.Context, arg InsertRecommendationOutcomeIfChangedParams) (int64, error)
	InsertRecommendationSnapshot(ctx context.Context, arg InsertRecommendationSnapshotParams) (RecommendationSnapshot, error)
	ListBacktestReplayRows(ctx context.Context, arg ListBacktestReplayRowsParams) ([]ListBacktestReplayRowsRow, error)
	ListLatestOdds(ctx context.Context, arg ListLatestOddsParams) ([]ListLatestOddsRow, error)
	ListModelPredictionsForSportSeason(ctx context.Context, arg ListModelPredictionsForSportSeasonParams) ([]ModelPrediction, error)
	ListRecommendationPerformanceSnapshots(ctx context.Context, arg ListRecommendationPerformanceSnapshotsParams) ([]ListRecommendationPerformanceSnapshotsRow, error)
	ListRecommendationSnapshots(ctx context.Context, arg ListRecommendationSnapshotsParams) ([]RecommendationSnapshot, error)
	ListUpcomingGames(ctx context.Context, limit int32) ([]Game, error)
	ListUpcomingWeatherGames(ctx context.Context, arg ListUpcomingWeatherGamesParams) ([]Game, error)
	UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error)
	UpsertGameWeatherSnapshot(ctx context.Context, arg UpsertGameWeatherSnapshotParams) error
	UpsertMLBPitcherStats(ctx context.Context, arg UpsertMLBPitcherStatsParams) error
	UpsertMLBTeamStats(ctx context.Context, arg UpsertMLBTeamStatsParams) error
	UpsertModelPrediction(ctx context.Context, arg UpsertModelPredictionParams) (ModelPrediction, error)
	UpsertNBATeamStats(ctx context.Context, arg UpsertNBATeamStatsParams) error
	UpsertNFLTeamStats(ctx context.Context, arg UpsertNFLTeamStatsParams) error
	UpsertNHLTeamStats(ctx context.Context, arg UpsertNHLTeamStatsParams) error
	UpsertPlayerInjuryReport(ctx context.Context, arg UpsertPlayerInjuryReportParams) error
}

var _ Querier = (*Queries)(nil)
