// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_performance.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRecommendationOutcomeIfChanged = `-- name: InsertRecommendationOutcomeIfChanged :execrows
INSERT INTO recommendation_outcomes (
    snapshot_id,
    evaluation_status,
    close_american_odds,
    close_probability,
    realized_result,
    clv_delta,
    settled_at,
    notes,
    metadata
)
SELECT
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9::jsonb
WHERE NOT EXISTS (
    SELECT 1
    FROM recommendation_outcomes AS ro
    WHERE ro.snapshot_id = $1
      AND ro.evaluation_status = $2
      AND ro.close_american_odds IS NOT DISTINCT FROM $3
      AND ro.close_probability IS NOT DISTINCT FROM $4
      AND ro.realized_result IS NOT DISTINCT FROM $5
      AND ro.clv_delta IS NOT DISTINCT FROM $6
      AND ro.settled_at IS NOT DISTINCT FROM $7
      AND ro.notes = $8
      AND ro.metadata = $9::jsonb
)
`

type InsertRecommendationOutcomeIfChangedParams struct {
	SnapshotID        int64              `json:"snapshot_id"`
	EvaluationStatus  string             `json:"evaluation_status"`
	CloseAmericanOdds *int32             `json:"close_american_odds"`
	CloseProbability  *float64           `json:"close_probability"`
	RealizedResult    *string            `json:"realized_result"`
	ClvDelta          *float64           `json:"clv_delta"`
	SettledAt         pgtype.Timestamptz `json:"settled_at"`
	Notes             string             `json:"notes"`
	Metadata          json.RawMessage    `json:"metadata"`
}

func (q *Queries) InsertRecommendationOutcomeIfChanged(ctx context.Context, arg InsertRecommendationOutcomeIfChangedParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRecommendationOutcomeIfChanged,
		arg.SnapshotID,
		arg.EvaluationStatus,
		arg.CloseAmericanOdds,
		arg.CloseProbability,
		arg.RealizedResult,
		arg.ClvDelta,
		arg.SettledAt,
		arg.Notes,
		arg.Metadata,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRecommendationPerformanceSnapshots = `-- name: ListRecommendationPerformanceSnapshots :many
SELECT
    rs.id AS snapshot_id,
    rs.generated_at,
    rs.sport,
    rs.game_id,
    g.home_team,
    g.away_team,
    rs.event_time,
    rs.event_date,
    rs.market_key,
    rs.recommended_side,
    rs.best_book,
    rs.best_american_odds,
    rs.model_probability,
    rs.market_probability,
    rs.edge,
    rs.suggested_stake_fraction,
    rs.suggested_stake_cents,
    rs.bankroll_check_pass,
    rs.bankroll_check_reason,
    rs.rank_score,
    rs.metadata AS snapshot_metadata,
    COALESCE(close_line.id, 0)::BIGINT AS close_line_id,
    COALESCE(close_line.price_american, 0)::INTEGER AS close_american_odds,
    COALESCE(close_line.implied_probability, 0)::DOUBLE PRECISION AS close_probability,
    COALESCE(close_line.captured_at, rs.event_time) AS close_captured_at,
    COALESCE(close_line.raw_json, '{}'::jsonb) AS close_raw_json,
    COALESCE(latest_outcome.id, 0)::BIGINT AS persisted_outcome_id,
    COALESCE(latest_outcome.evaluation_status, '') AS persisted_status,
    latest_outcome.close_american_odds AS persisted_close_american_odds,
    latest_outcome.close_probability AS persisted_close_probability,
    latest_outcome.realized_result AS persisted_realized_result,
    latest_outcome.clv_delta AS persisted_clv_delta,
    latest_outcome.settled_at AS persisted_settled_at,
    COALESCE(latest_outcome.notes, '') AS persisted_notes,
    COALESCE(latest_outcome.metadata, '{}'::jsonb) AS persisted_metadata,
    COALESCE(latest_outcome.created_at, rs.generated_at) AS persisted_created_at
FROM recommendation_snapshots AS rs
JOIN games AS g
    ON g.id = rs.game_id
LEFT JOIN LATERAL (
    SELECT
        oh.price_american,
        oh.implied_probability,
        oh.captured_at,
        oh.raw_json,
        oh.id
    FROM odds_history AS oh
    WHERE oh.game_id = rs.game_id
      AND oh.market_key = rs.market_key
      AND oh.outcome_side = rs.recommended_side
      AND (oh.book_key = rs.best_book OR oh.book_name = rs.best_book)
      AND oh.captured_at <= rs.event_time
    ORDER BY oh.captured_at DESC, oh.id DESC
    LIMIT 1
) AS close_line ON TRUE
LEFT JOIN LATERAL (
    SELECT
        ro.evaluation_status,
        ro.close_american_odds,
        ro.close_probability,
        ro.realized_result,
        ro.clv_delta,
        ro.settled_at,
        ro.notes,
        ro.metadata,
        ro.created_at,
        ro.id
    FROM recommendation_outcomes AS ro
    WHERE ro.snapshot_id = rs.id
    ORDER BY ro.created_at DESC, ro.id DESC
    LIMIT 1
) AS latest_outcome ON TRUE
WHERE
    (
        $1::text IS NULL
        OR rs.sport = $1::text
    )
    AND (
        $2::date IS NULL
        OR rs.event_date >= $2::date
    )
    AND (
        $3::date IS NULL
        OR rs.event_date <= $3::date
    )
ORDER BY rs.generated_at DESC, rs.rank_score DESC, rs.id ASC
LIMIT $4
`

type ListRecommendationPerformanceSnapshotsParams struct {
	Sport    *string     `json:"sport"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	RowLimit int32       `json:"row_limit"`
}

type ListRecommendationPerformanceSnapshotsRow struct {
	SnapshotID                 int64              `json:"snapshot_id"`
	GeneratedAt                pgtype.Timestamptz `json:"generated_at"`
	Sport                      string             `json:"sport"`
	GameID                     int64              `json:"game_id"`
	HomeTeam                   string             `json:"home_team"`
	AwayTeam                   string             `json:"away_team"`
	EventTime                  pgtype.Timestamptz `json:"event_time"`
	EventDate                  pgtype.Date        `json:"event_date"`
	MarketKey                  string             `json:"market_key"`
	RecommendedSide            string             `json:"recommended_side"`
	BestBook                   string             `json:"best_book"`
	BestAmericanOdds           int32              `json:"best_american_odds"`
	ModelProbability           float64            `json:"model_probability"`
	MarketProbability          float64            `json:"market_probability"`
	Edge                       float64            `json:"edge"`
	SuggestedStakeFraction     float64            `json:"suggested_stake_fraction"`
	SuggestedStakeCents        int64              `json:"suggested_stake_cents"`
	BankrollCheckPass          bool               `json:"bankroll_check_pass"`
	BankrollCheckReason        string             `json:"bankroll_check_reason"`
	RankScore                  float64            `json:"rank_score"`
	SnapshotMetadata           json.RawMessage    `json:"snapshot_metadata"`
	CloseLineID                int64              `json:"close_line_id"`
	CloseAmericanOdds          int32              `json:"close_american_odds"`
	CloseProbability           float64            `json:"close_probability"`
	CloseCapturedAt            pgtype.Timestamptz `json:"close_captured_at"`
	CloseRawJson               json.RawMessage    `json:"close_raw_json"`
	PersistedOutcomeID         int64              `json:"persisted_outcome_id"`
	PersistedStatus            string             `json:"persisted_status"`
	PersistedCloseAmericanOdds *int32             `json:"persisted_close_american_odds"`
	PersistedCloseProbability  *float64           `json:"persisted_close_probability"`
	PersistedRealizedResult    *string            `json:"persisted_realized_result"`
	PersistedClvDelta          *float64           `json:"persisted_clv_delta"`
	PersistedSettledAt         pgtype.Timestamptz `json:"persisted_settled_at"`
	PersistedNotes             string             `json:"persisted_notes"`
	PersistedMetadata          json.RawMessage    `json:"persisted_metadata"`
	PersistedCreatedAt         pgtype.Timestamptz `json:"persisted_created_at"`
}

func (q *Queries) ListRecommendationPerformanceSnapshots(ctx context.Context, arg ListRecommendationPerformanceSnapshotsParams) ([]ListRecommendationPerformanceSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listRecommendationPerformanceSnapshots,
		arg.Sport,
		arg.DateFrom,
		arg.DateTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecommendationPerformanceSnapshotsRow
	for rows.Next() {
		var i ListRecommendationPerformanceSnapshotsRow
		if err := rows.Scan(
			&i.SnapshotID,
			&i.GeneratedAt,
			&i.Sport,
			&i.GameID,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.EventTime,
			&i.EventDate,
			&i.MarketKey,
			&i.RecommendedSide,
			&i.BestBook,
			&i.BestAmericanOdds,
			&i.ModelProbability,
			&i.MarketProbability,
			&i.Edge,
			&i.SuggestedStakeFraction,
			&i.SuggestedStakeCents,
			&i.BankrollCheckPass,
			&i.BankrollCheckReason,
			&i.RankScore,
			&i.SnapshotMetadata,
			&i.CloseLineID,
			&i.CloseAmericanOdds,
			&i.CloseProbability,
			&i.CloseCapturedAt,
			&i.CloseRawJson,
			&i.PersistedOutcomeID,
			&i.PersistedStatus,
			&i.PersistedCloseAmericanOdds,
			&i.PersistedCloseProbability,
			&i.PersistedRealizedResult,
			&i.PersistedClvDelta,
			&i.PersistedSettledAt,
			&i.PersistedNotes,
			&i.PersistedMetadata,
			&i.PersistedCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
