// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRecommendationSnapshot = `-- name: InsertRecommendationSnapshot :one
INSERT INTO recommendation_snapshots (
    generated_at,
    sport,
    game_id,
    event_time,
    event_date,
    market_key,
    recommended_side,
    best_book,
    best_american_odds,
    model_probability,
    market_probability,
    edge,
    suggested_stake_fraction,
    suggested_stake_cents,
    bankroll_check_pass,
    bankroll_check_reason,
    rank_score,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, generated_at, sport, game_id, event_time, event_date, market_key, recommended_side, best_book, best_american_odds, model_probability, market_probability, edge, suggested_stake_fraction, suggested_stake_cents, bankroll_check_pass, bankroll_check_reason, rank_score, metadata, created_at
`

type InsertRecommendationSnapshotParams struct {
	GeneratedAt            pgtype.Timestamptz `json:"generated_at"`
	Sport                  string             `json:"sport"`
	GameID                 int64              `json:"game_id"`
	EventTime              pgtype.Timestamptz `json:"event_time"`
	EventDate              pgtype.Date        `json:"event_date"`
	MarketKey              string             `json:"market_key"`
	RecommendedSide        string             `json:"recommended_side"`
	BestBook               string             `json:"best_book"`
	BestAmericanOdds       int32              `json:"best_american_odds"`
	ModelProbability       float64            `json:"model_probability"`
	MarketProbability      float64            `json:"market_probability"`
	Edge                   float64            `json:"edge"`
	SuggestedStakeFraction float64            `json:"suggested_stake_fraction"`
	SuggestedStakeCents    int64              `json:"suggested_stake_cents"`
	BankrollCheckPass      bool               `json:"bankroll_check_pass"`
	BankrollCheckReason    string             `json:"bankroll_check_reason"`
	RankScore              float64            `json:"rank_score"`
	Metadata               json.RawMessage    `json:"metadata"`
}

func (q *Queries) InsertRecommendationSnapshot(ctx context.Context, arg InsertRecommendationSnapshotParams) (RecommendationSnapshot, error) {
	row := q.db.QueryRow(ctx, insertRecommendationSnapshot,
		arg.GeneratedAt,
		arg.Sport,
		arg.GameID,
		arg.EventTime,
		arg.EventDate,
		arg.MarketKey,
		arg.RecommendedSide,
		arg.BestBook,
		arg.BestAmericanOdds,
		arg.ModelProbability,
		arg.MarketProbability,
		arg.Edge,
		arg.SuggestedStakeFraction,
		arg.SuggestedStakeCents,
		arg.BankrollCheckPass,
		arg.BankrollCheckReason,
		arg.RankScore,
		arg.Metadata,
	)
	var i RecommendationSnapshot
	err := row.Scan(
		&i.ID,
		&i.GeneratedAt,
		&i.Sport,
		&i.GameID,
		&i.EventTime,
		&i.EventDate,
		&i.MarketKey,
		&i.RecommendedSide,
		&i.BestBook,
		&i.BestAmericanOdds,
		&i.ModelProbability,
		&i.MarketProbability,
		&i.Edge,
		&i.SuggestedStakeFraction,
		&i.SuggestedStakeCents,
		&i.BankrollCheckPass,
		&i.BankrollCheckReason,
		&i.RankScore,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listRecommendationSnapshots = `-- name: ListRecommendationSnapshots :many
SELECT
    id,
    generated_at,
    sport,
    game_id,
    event_time,
    event_date,
    market_key,
    recommended_side,
    best_book,
    best_american_odds,
    model_probability,
    market_probability,
    edge,
    suggested_stake_fraction,
    suggested_stake_cents,
    bankroll_check_pass,
    bankroll_check_reason,
    rank_score,
    metadata,
    created_at
FROM recommendation_snapshots
WHERE
    (
        $1::text IS NULL
        OR sport = $1::text
    )
    AND (
        $2::date IS NULL
        OR event_date = $2::date
    )
ORDER BY rank_score DESC, generated_at DESC, id ASC
LIMIT $3
`

type ListRecommendationSnapshotsParams struct {
	Sport     *string     `json:"sport"`
	EventDate pgtype.Date `json:"event_date"`
	RowLimit  int32       `json:"row_limit"`
}

func (q *Queries) ListRecommendationSnapshots(ctx context.Context, arg ListRecommendationSnapshotsParams) ([]RecommendationSnapshot, error) {
	rows, err := q.db.Query(ctx, listRecommendationSnapshots, arg.Sport, arg.EventDate, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationSnapshot
	for rows.Next() {
		var i RecommendationSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.GeneratedAt,
			&i.Sport,
			&i.GameID,
			&i.EventTime,
			&i.EventDate,
			&i.MarketKey,
			&i.RecommendedSide,
			&i.BestBook,
			&i.BestAmericanOdds,
			&i.ModelProbability,
			&i.MarketProbability,
			&i.Edge,
			&i.SuggestedStakeFraction,
			&i.SuggestedStakeCents,
			&i.BankrollCheckPass,
			&i.BankrollCheckReason,
			&i.RankScore,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
