// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendation_calibration_alert_runs.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRecommendationCalibrationAlertRun = `-- name: InsertRecommendationCalibrationAlertRun :execrows
INSERT INTO recommendation_calibration_alert_runs (
    sport,
    request_hash,
    run_group_hash,
    mode,
    step_index,
    step_count,
    window_days,
    current_from,
    current_to,
    baseline_from,
    baseline_to,
    bucket_count,
    row_limit,
    min_settled_overall,
    min_settled_per_bucket,
    warn_ece_delta,
    critical_ece_delta,
    warn_brier_delta,
    critical_brier_delta,
    alert_level,
    reasons,
    current_overall_ece,
    baseline_overall_ece,
    ece_delta,
    current_overall_brier,
    baseline_overall_brier,
    brier_delta,
    current_settled_rows,
    baseline_settled_rows,
    insufficient_overall_windows,
    current_insufficient_buckets,
    baseline_insufficient_buckets,
    payload
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21::jsonb,
    $22,
    $23,
    $24,
    $25,
    $26,
    $27,
    $28,
    $29,
    $30,
    $31,
    $32,
    $33::jsonb
)
`

type InsertRecommendationCalibrationAlertRunParams struct {
	Sport                       string          `json:"sport"`
	RequestHash                 string          `json:"request_hash"`
	RunGroupHash                string          `json:"run_group_hash"`
	Mode                        string          `json:"mode"`
	StepIndex                   int32           `json:"step_index"`
	StepCount                   int32           `json:"step_count"`
	WindowDays                  *int32          `json:"window_days"`
	CurrentFrom                 pgtype.Date     `json:"current_from"`
	CurrentTo                   pgtype.Date     `json:"current_to"`
	BaselineFrom                pgtype.Date     `json:"baseline_from"`
	BaselineTo                  pgtype.Date     `json:"baseline_to"`
	BucketCount                 int32           `json:"bucket_count"`
	RowLimit                    int32           `json:"row_limit"`
	MinSettledOverall           int32           `json:"min_settled_overall"`
	MinSettledPerBucket         int32           `json:"min_settled_per_bucket"`
	WarnEceDelta                float64         `json:"warn_ece_delta"`
	CriticalEceDelta            float64         `json:"critical_ece_delta"`
	WarnBrierDelta              float64         `json:"warn_brier_delta"`
	CriticalBrierDelta          float64         `json:"critical_brier_delta"`
	AlertLevel                  string          `json:"alert_level"`
	Reasons                     json.RawMessage `json:"reasons"`
	CurrentOverallEce           float64         `json:"current_overall_ece"`
	BaselineOverallEce          float64         `json:"baseline_overall_ece"`
	EceDelta                    float64         `json:"ece_delta"`
	CurrentOverallBrier         float64         `json:"current_overall_brier"`
	BaselineOverallBrier        float64         `json:"baseline_overall_brier"`
	BrierDelta                  float64         `json:"brier_delta"`
	CurrentSettledRows          int32           `json:"current_settled_rows"`
	BaselineSettledRows         int32           `json:"baseline_settled_rows"`
	InsufficientOverallWindows  int32           `json:"insufficient_overall_windows"`
	CurrentInsufficientBuckets  int32           `json:"current_insufficient_buckets"`
	BaselineInsufficientBuckets int32           `json:"baseline_insufficient_buckets"`
	Payload                     []byte          `json:"payload"`
}

func (q *Queries) InsertRecommendationCalibrationAlertRun(ctx context.Context, arg InsertRecommendationCalibrationAlertRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRecommendationCalibrationAlertRun,
		arg.Sport,
		arg.RequestHash,
		arg.RunGroupHash,
		arg.Mode,
		arg.StepIndex,
		arg.StepCount,
		arg.WindowDays,
		arg.CurrentFrom,
		arg.CurrentTo,
		arg.BaselineFrom,
		arg.BaselineTo,
		arg.BucketCount,
		arg.RowLimit,
		arg.MinSettledOverall,
		arg.MinSettledPerBucket,
		arg.WarnEceDelta,
		arg.CriticalEceDelta,
		arg.WarnBrierDelta,
		arg.CriticalBrierDelta,
		arg.AlertLevel,
		arg.Reasons,
		arg.CurrentOverallEce,
		arg.BaselineOverallEce,
		arg.EceDelta,
		arg.CurrentOverallBrier,
		arg.BaselineOverallBrier,
		arg.BrierDelta,
		arg.CurrentSettledRows,
		arg.BaselineSettledRows,
		arg.InsufficientOverallWindows,
		arg.CurrentInsufficientBuckets,
		arg.BaselineInsufficientBuckets,
		arg.Payload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRecommendationCalibrationAlertRuns = `-- name: ListRecommendationCalibrationAlertRuns :many
SELECT
    id,
    sport,
    request_hash,
    run_group_hash,
    mode,
    step_index,
    step_count,
    window_days,
    current_from,
    current_to,
    baseline_from,
    baseline_to,
    bucket_count,
    row_limit,
    min_settled_overall,
    min_settled_per_bucket,
    warn_ece_delta,
    critical_ece_delta,
    warn_brier_delta,
    critical_brier_delta,
    alert_level,
    reasons,
    current_overall_ece,
    baseline_overall_ece,
    ece_delta,
    current_overall_brier,
    baseline_overall_brier,
    brier_delta,
    current_settled_rows,
    baseline_settled_rows,
    insufficient_overall_windows,
    current_insufficient_buckets,
    baseline_insufficient_buckets,
    payload,
    created_at
FROM recommendation_calibration_alert_runs
WHERE
    (
        $1::text IS NULL
        OR sport = $1::text
    )
    AND (
        $2::date IS NULL
        OR created_at::date >= $2::date
    )
    AND (
        $3::date IS NULL
        OR created_at::date <= $3::date
    )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListRecommendationCalibrationAlertRunsParams struct {
	Sport    *string     `json:"sport"`
	DateFrom pgtype.Date `json:"date_from"`
	DateTo   pgtype.Date `json:"date_to"`
	RowLimit int32       `json:"row_limit"`
}

func (q *Queries) ListRecommendationCalibrationAlertRuns(ctx context.Context, arg ListRecommendationCalibrationAlertRunsParams) ([]RecommendationCalibrationAlertRun, error) {
	rows, err := q.db.Query(ctx, listRecommendationCalibrationAlertRuns,
		arg.Sport,
		arg.DateFrom,
		arg.DateTo,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationCalibrationAlertRun
	for rows.Next() {
		var i RecommendationCalibrationAlertRun
		if err := rows.Scan(
			&i.ID,
			&i.Sport,
			&i.RequestHash,
			&i.RunGroupHash,
			&i.Mode,
			&i.StepIndex,
			&i.StepCount,
			&i.WindowDays,
			&i.CurrentFrom,
			&i.CurrentTo,
			&i.BaselineFrom,
			&i.BaselineTo,
			&i.BucketCount,
			&i.RowLimit,
			&i.MinSettledOverall,
			&i.MinSettledPerBucket,
			&i.WarnEceDelta,
			&i.CriticalEceDelta,
			&i.WarnBrierDelta,
			&i.CriticalBrierDelta,
			&i.AlertLevel,
			&i.Reasons,
			&i.CurrentOverallEce,
			&i.BaselineOverallEce,
			&i.EceDelta,
			&i.CurrentOverallBrier,
			&i.BaselineOverallBrier,
			&i.BrierDelta,
			&i.CurrentSettledRows,
			&i.BaselineSettledRows,
			&i.InsufficientOverallWindows,
			&i.CurrentInsufficientBuckets,
			&i.BaselineInsufficientBuckets,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
