// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: weather.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const listUpcomingWeatherGames = `-- name: ListUpcomingWeatherGames :many
SELECT id, source, external_id, sport, home_team, away_team, commence_time, created_at, updated_at
FROM games
WHERE sport = ANY($1::text[])
  AND commence_time >= $2
  AND commence_time < $3
ORDER BY commence_time ASC
`

type ListUpcomingWeatherGamesParams struct {
	Sports      []string           `json:"sports"`
	WindowStart pgtype.Timestamptz `json:"window_start"`
	WindowEnd   pgtype.Timestamptz `json:"window_end"`
}

func (q *Queries) ListUpcomingWeatherGames(ctx context.Context, arg ListUpcomingWeatherGamesParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listUpcomingWeatherGames, arg.Sports, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Game
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Sport,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.CommenceTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGameWeatherSnapshot = `-- name: UpsertGameWeatherSnapshot :exec
INSERT INTO game_weather_snapshots (
    game_id,
    source,
    forecast_time,
    venue_name,
    venue_timezone,
    latitude,
    longitude,
    roof_type,
    weather_code,
    temperature_f,
    apparent_temperature_f,
    precipitation_probability,
    precipitation_inches,
    wind_speed_mph,
    wind_gust_mph,
    wind_direction_degrees,
    raw_json
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17
)
ON CONFLICT (game_id, source) DO UPDATE
SET
    forecast_time = EXCLUDED.forecast_time,
    venue_name = EXCLUDED.venue_name,
    venue_timezone = EXCLUDED.venue_timezone,
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    roof_type = EXCLUDED.roof_type,
    weather_code = EXCLUDED.weather_code,
    temperature_f = EXCLUDED.temperature_f,
    apparent_temperature_f = EXCLUDED.apparent_temperature_f,
    precipitation_probability = EXCLUDED.precipitation_probability,
    precipitation_inches = EXCLUDED.precipitation_inches,
    wind_speed_mph = EXCLUDED.wind_speed_mph,
    wind_gust_mph = EXCLUDED.wind_gust_mph,
    wind_direction_degrees = EXCLUDED.wind_direction_degrees,
    raw_json = EXCLUDED.raw_json,
    updated_at = NOW()
WHERE
    game_weather_snapshots.forecast_time IS DISTINCT FROM EXCLUDED.forecast_time
    OR game_weather_snapshots.venue_name IS DISTINCT FROM EXCLUDED.venue_name
    OR game_weather_snapshots.venue_timezone IS DISTINCT FROM EXCLUDED.venue_timezone
    OR game_weather_snapshots.latitude IS DISTINCT FROM EXCLUDED.latitude
    OR game_weather_snapshots.longitude IS DISTINCT FROM EXCLUDED.longitude
    OR game_weather_snapshots.roof_type IS DISTINCT FROM EXCLUDED.roof_type
    OR game_weather_snapshots.weather_code IS DISTINCT FROM EXCLUDED.weather_code
    OR game_weather_snapshots.temperature_f IS DISTINCT FROM EXCLUDED.temperature_f
    OR game_weather_snapshots.apparent_temperature_f IS DISTINCT FROM EXCLUDED.apparent_temperature_f
    OR game_weather_snapshots.precipitation_probability IS DISTINCT FROM EXCLUDED.precipitation_probability
    OR game_weather_snapshots.precipitation_inches IS DISTINCT FROM EXCLUDED.precipitation_inches
    OR game_weather_snapshots.wind_speed_mph IS DISTINCT FROM EXCLUDED.wind_speed_mph
    OR game_weather_snapshots.wind_gust_mph IS DISTINCT FROM EXCLUDED.wind_gust_mph
    OR game_weather_snapshots.wind_direction_degrees IS DISTINCT FROM EXCLUDED.wind_direction_degrees
    OR game_weather_snapshots.raw_json IS DISTINCT FROM EXCLUDED.raw_json
`

type UpsertGameWeatherSnapshotParams struct {
	GameID                   int64              `json:"game_id"`
	Source                   string             `json:"source"`
	ForecastTime             pgtype.Timestamptz `json:"forecast_time"`
	VenueName                string             `json:"venue_name"`
	VenueTimezone            string             `json:"venue_timezone"`
	Latitude                 float64            `json:"latitude"`
	Longitude                float64            `json:"longitude"`
	RoofType                 string             `json:"roof_type"`
	WeatherCode              *int32             `json:"weather_code"`
	TemperatureF             *float64           `json:"temperature_f"`
	ApparentTemperatureF     *float64           `json:"apparent_temperature_f"`
	PrecipitationProbability *float64           `json:"precipitation_probability"`
	PrecipitationInches      *float64           `json:"precipitation_inches"`
	WindSpeedMph             *float64           `json:"wind_speed_mph"`
	WindGustMph              *float64           `json:"wind_gust_mph"`
	WindDirectionDegrees     *int32             `json:"wind_direction_degrees"`
	RawJson                  json.RawMessage    `json:"raw_json"`
}

func (q *Queries) UpsertGameWeatherSnapshot(ctx context.Context, arg UpsertGameWeatherSnapshotParams) error {
	_, err := q.db.Exec(ctx, upsertGameWeatherSnapshot,
		arg.GameID,
		arg.Source,
		arg.ForecastTime,
		arg.VenueName,
		arg.VenueTimezone,
		arg.Latitude,
		arg.Longitude,
		arg.RoofType,
		arg.WeatherCode,
		arg.TemperatureF,
		arg.ApparentTemperatureF,
		arg.PrecipitationProbability,
		arg.PrecipitationInches,
		arg.WindSpeedMph,
		arg.WindGustMph,
		arg.WindDirectionDegrees,
		arg.RawJson,
	)
	return err
}
